// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hingew/hsfl-master-ai-cloud-engineering/templating-service/templates/controller (interfaces: IController)

// Package mock_controller is a generated GoMock package.
package mock_

import (
        http "net/http"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockIController is a mock of IController interface.
type MockIController struct {
        ctrl     *gomock.Controller
        recorder *MockIControllerMockRecorder
}

// MockIControllerMockRecorder is the mock recorder for MockIController.
type MockIControllerMockRecorder struct {
        mock *MockIController
}

// NewMockIController creates a new mock instance.
func NewMockIController(ctrl *gomock.Controller) *MockIController {
        mock := &MockIController{ctrl: ctrl}
        mock.recorder = &MockIControllerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIController) EXPECT() *MockIControllerMockRecorder {
        return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockIController) CreateTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "CreateTemplate", arg0, arg1)
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockIControllerMockRecorder) CreateTemplate(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockIController)(nil).CreateTemplate), arg0, arg1)    
}

// DeleteTemplate mocks base method.
func (m *MockIController) DeleteTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "DeleteTemplate", arg0, arg1)
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockIControllerMockRecorder) DeleteTemplate(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockIController)(nil).DeleteTemplate), arg0, arg1)    
}

// GetAllTemplates mocks base method.
func (m *MockIController) GetAllTemplates(arg0 http.ResponseWriter, arg1 *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "GetAllTemplates", arg0, arg1)
}

// GetAllTemplates indicates an expected call of GetAllTemplates.
func (mr *MockIControllerMockRecorder) GetAllTemplates(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTemplates", reflect.TypeOf((*MockIController)(nil).GetAllTemplates), arg0, arg1)  
}

// GetTemplate mocks base method.
func (m *MockIController) GetTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "GetTemplate", arg0, arg1)
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockIControllerMockRecorder) GetTemplate(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockIController)(nil).GetTemplate), arg0, arg1)
}

// UpdateTemplate mocks base method.
func (m *MockIController) UpdateTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "UpdateTemplate", arg0, arg1)
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockIControllerMockRecorder) UpdateTemplate(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockIController)(nil).UpdateTemplate), arg0, arg1)    
}