version: '3.9'

services:
  reverse_proxy:
    build:
      context: ./ 
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - 3000:3000
    environment:
      - WEB_ENDPOINT=http://web:3000
      - TEMPLATE_ENDPOINT=http://templates:3000
      - CREATION_ENDPOINT=http://creation:3000
      - USER_ENDPOINT=http://user:3000
      - WEB_ROUTES=/;/static/
      - TEMPLATE_ROUTES=/api/templates;/api/templates/:id
      - CREATION_ROUTES=/api/render/:id
      - USER_ROUTES=/auth/register;/auth/login
    volumes:
      - ./services/api-gateway/config.yml:/app/config.yml
    depends_on:
      - web
      - templates
      - creation
  
  web:
    build:
      context: ./ 
      dockerfile: ./services/web-service/Dockerfile
    ports:
      - 3001:3000
    environment:
      - TEMPLATE_ENDPOINT=http://templates:3000
    links:
      - templates
    
  templates:
    build:
      context: ./
      dockerfile: ./services/templateing-service/Dockerfile
    ports:
      - 3002:3000
    environment:
      - USE_TESTDATA=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
    volumes:
      - ./services/templateing-service/config.yml:/app/config.yml
      - ./services/templateing-service/test_data.json:/app/test_data.json
    depends_on:
      postgres:
        condition: service_healthy
  
  creation:
    build: 
      context: ./
      dockerfile: ./services/creation-service/Dockerfile
    volumes:
      - ./services/creation-service/config.yml:/app/config.yml
    ports:
      - 3003:3000
    links:
      - templates

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./services/templateing-service/sql:/docker-entrypoint-initdb.d
