version: '3.9'

services:
  reverse_proxy:
    image: hauing/api-gateway:develop
    build:
      context: ./ 
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - 3000:3000
    environment:
      - WEB_ENDPOINT=$WEB_ENDPOINT
      - TEMPLATE_ENDPOINT=$TEMPLATE_ENDPOINT
      - CREATION_ENDPOINT=$CREATION_ENDPOINT
      - USER_ENDPOINT=$USER_ENDPOINT
    depends_on:
      - web
      - templates
      - creation
  
  web:
    image: hauing/web-service:develop
    build:
      context: ./ 
      dockerfile: ./services/web-service/Dockerfile
    ports:
      - 3001:3000
    links:
      - templates
    
  templates:
    image: hauing/templateing-service:develop
    build:
      context: ./
      dockerfile: ./services/templateing-service/Dockerfile
    ports:
      - 3002:3000
      - 3010:3001
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
      - USER_GRPC_ENDPOINT=$USER_GRPC_ENDPOINT
    volumes:
      - ./services/templateing-service/test_data.json:/app/test_data.json
    depends_on:
      postgres:
        condition: service_healthy
  
  creation:
    image: hauing/creation-service:develop
    build: 
      context: ./
      dockerfile: ./services/creation-service/Dockerfile
    environment:
      - TEMPLATE_GRPC_ENDPOINT=$TEMPLATE_GRPC_ENDPOINT
    ports:
      - 3003:3000
    links:
      - templates
    depends_on:
      - templates

  user:
    image: hauing/user-service:develop
    build:
      context: ./
      dockerfile: ./services/user-service/Dockerfile
    ports:
      - 3004:3000
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
      - AUTH_PRIVATE_KEY=$AUTH_PRIVATE_KEY
      - AUTH_PUBLIC_KEY=$AUTH_PUBLIC_KEY
      - PORT=3000
    volumes:
      - ./services/templateing-service/test_data.json:/app/test_data.json
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
