// Code generated by MockGen. DO NOT EDIT.
// Source: templates/controller/controller_interface.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=_mocks/controller.go -source=templates/controller/controller_interface.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockControllerInterface is a mock of ControllerInterface interface.
type MockControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockControllerInterfaceMockRecorder
}

// MockControllerInterfaceMockRecorder is the mock recorder for MockControllerInterface.
type MockControllerInterfaceMockRecorder struct {
	mock *MockControllerInterface
}

// NewMockControllerInterface creates a new mock instance.
func NewMockControllerInterface(ctrl *gomock.Controller) *MockControllerInterface {
	mock := &MockControllerInterface{ctrl: ctrl}
	mock.recorder = &MockControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerInterface) EXPECT() *MockControllerInterfaceMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockControllerInterface) CreateTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTemplate", arg0, arg1)
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockControllerInterfaceMockRecorder) CreateTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockControllerInterface)(nil).CreateTemplate), arg0, arg1)
}

// DeleteTemplate mocks base method.
func (m *MockControllerInterface) DeleteTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteTemplate", arg0, arg1)
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockControllerInterfaceMockRecorder) DeleteTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockControllerInterface)(nil).DeleteTemplate), arg0, arg1)
}

// GetAllTemplates mocks base method.
func (m *MockControllerInterface) GetAllTemplates(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAllTemplates", arg0, arg1)
}

// GetAllTemplates indicates an expected call of GetAllTemplates.
func (mr *MockControllerInterfaceMockRecorder) GetAllTemplates(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTemplates", reflect.TypeOf((*MockControllerInterface)(nil).GetAllTemplates), arg0, arg1)
}

// GetTemplate mocks base method.
func (m *MockControllerInterface) GetTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTemplate", arg0, arg1)
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockControllerInterfaceMockRecorder) GetTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockControllerInterface)(nil).GetTemplate), arg0, arg1)
}

// GetTemplateWithCoalecing mocks base method.
func (m *MockControllerInterface) GetTemplateWithCoalecing(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTemplateWithCoalecing", arg0, arg1)
}

// GetTemplateWithCoalecing indicates an expected call of GetTemplateWithCoalecing.
func (mr *MockControllerInterfaceMockRecorder) GetTemplateWithCoalecing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateWithCoalecing", reflect.TypeOf((*MockControllerInterface)(nil).GetTemplateWithCoalecing), arg0, arg1)
}

// UpdateTemplate mocks base method.
func (m *MockControllerInterface) UpdateTemplate(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTemplate", arg0, arg1)
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockControllerInterfaceMockRecorder) UpdateTemplate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockControllerInterface)(nil).UpdateTemplate), arg0, arg1)
}
