name: User-Service Tests

on:
  push:
    paths:
      - 'services/user-service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go get .

    - name: Go test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic