{
 "title": "Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Util [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - rate(node_cpu_seconds_total{mode=\"idle\", kubernetes_name=\"\"}[1m])) * 100",
     "legendFormat": "{{instance}}_cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Util [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{kubernetes_namespace=\"\"} / node_memory_MemTotal_bytes{kubernetes_namespace=\"\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{kubernetes_name=\"\", device=\"eth0\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_name=\"\", device=\"eth0\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}