apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: hauing/api-gateway:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: WEB_ENDPOINT
              value: "http://web-service:3001"
            - name: TEMPLATE_ENDPOINT
              value: "http://templateing-service:3002"
            - name: CREATION_ENDPOINT
              value: "http://creation-service:3003"
            - name: USER_ENDPOINT
              value: "http://user-service:3004"
            - name: WEB_ROUTES
              value: "/;/static/"
            - name: TEMPLATE_ROUTES
              value: "/api/templates;/api/templates/:id;/api/templates/:id/controller_coalescing;/api/templates/:id/gateway_coalescing"
            - name: CREATION_ROUTES
              value: "/api/render/:id"
            - name: USER_ROUTES
              value: "/auth/register;/auth/login"
