apiVersion: apps/v1
kind: Deployment
metadata:
  name: templateing-service-deployment
  labels:
    app: templateing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: templateing-service
  template:
    metadata:
      labels:
        app: templateing-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: templateing-service
          image: hauing/templateing-service:develop
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
            - containerPort: 3001
          envFrom:
          - secretRef:
             name: postgres-secret
