apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: hauing/user-service:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_HOST

        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PORT

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DBNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DBNAME

<<<<<<< HEAD
        - name: AUTH_SIGN_KEY 
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: AUTH_SIGN_KEY
=======
        - name: AUTH_PRIVATE_KEY 
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: AUTH_PRIVATE_KEY

        - name: AUTH_PUBLIC_KEY 
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: AUTH_PUBLIC_KEY
>>>>>>> 2eb6efa (feat(kubernetes): Update user-service deployment and secrets)
