apiVersion: v1
kind: Service
metadata:
  name: templateing-service
spec:
  selector:
    app: templateing-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3002 
  type: LoadBalancer