apiVersion: v1
kind: Service
metadata:
  name: templateing-service
spec:
  selector:
    app: templateing-service
  ports:
    - protocol: TCP
      name: "http"
      port: 3000
      targetPort: 3000
    # GRPC Server
    - protocol: TCP
      name: "grpc"
      port: 3001
      targetPort: 3001
  type: LoadBalancer
