name: Api-Gateway tests

on:
  push:
    paths:
      - 'services/api-gateway/**'
      - '.github/workflows/api-gateway.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      working-directory: ./services/api-gateway
      run: go get .

    - name: Go test
      working-directory: ./services/api-gateway
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: api-gateway


